name: Angular Build and Deploy

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 20

      - name: Build Angular app to prod
        working-directory: taskmanager-ui
        run: npm install && npm run build:prod

      - name: Deploy to GitHub Pages
        uses: vishnuprasad404/Task-Manager-UI@v1
        with:
          folder: taskmanager-ui/dist/browser
          branch: prod  
          token: ${{ secrets.SECRET_TOKEN }}