name: Github Pages Deploy

on:
  push:
    branches:
      - "development"

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [22.14]
    
    steps:
      - name: Checkout
        uses: actions/checkout@v1

      - name: Install and build
        working-directory: ./taskmanager-ui
        run: npm install && npm run gh-build && cp dist/angular-crash/index.html dist/angular-crash/404.html
      
      - name: Deploy
        uses: vishnuprasad404/taskmanager-ui@1.0.0
        with:
          branch: release/qa
          folder: dist/angular-crash      